### ISSUE TITLE
re-referencing Ion vortex_amplifier_projectile issues

### ISSUE THREAD

**Issue by L1ghtman2k** [Dinorush/TitanDebug#1]
original discussion: https://discord.com/channels/787948844100747274/937091632413700097/1188198565131071538

Log:
[message (6).txt](https://github.com/Dinorush/TitanDebug/files/13806448/message.6.txt)

**Comment by Dinorush** [comment]
Fixed by ea65fb3d2b8fc64c1782e218ce3a40199478f81d.
